//cart

export const INCREASE_TOTAL = 'INCREASE_TOTAL';
export const DECREASE_TOTAL = 'DECREASE_TOTAL';
export const FETCHING_CATS_STARTED = 'FETCHING_CATS_STARTED';
export const FETCHING_CATS_SUCCESS = 'FETCHING_CATS_SUCCESS';
export const FETCHING_CATS_ERROR = 'FETCHING_CATS_ERROR';
export const SUBSTRACT_FROM_TOTAL_PRICE = 'SUBSTRACT_FROM_TOTAL_PRICE';

//shipping

export const SET_FREE_SHIPPING = 'SET_FREE_SHIPPING';
export const CHOOSE_SHIPPING = 'CHOOSE_SHIPPING';